DEFAULT_ACCESS_TOKEN_EXPIRE_MINUTES = 30
DEFAULT_RESET_TOKEN_EXPIRE_MINUTES = 5
DEFAULT_RESET_OTP_LENGTH = 6
DEFAULT_JWT_ALGORITHM = "HS256"

APP_ENV_DEVELOPMENT = "development"
APP_ENV_PRODUCTION = "production"

APP_TAG_AUTH = "auth"
APP_TAG_USER = "user"
APP_TAG_STRATEGIES = "strategies"
